name: Test Message Workflow

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 1 minute
        run: |
          echo "Waiting for 1 minute..."
          sleep 60

      - name: Display message
        run: |
          echo "\n\n======================\nHello from the Test Message Workflow!\n======================"